version: '3.5'

services:
  node:
    image: node:10.16.0
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: npm run total-repos
    volumes: 
      - ./:/app
    working_dir: /app
    networks:
      - github-miner-network
    depends_on:
      - neo4j

  neo4j:
    image: bitnami/neo4j:3.5.8
    environment:
      - NEO4J_PASSWORD=password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    networks:
      - github-miner-network
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - ./data:/bitnami
      - ./bin:/app/bin

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    networks:
      - github-miner-network

networks:
  github-miner-network:
    driver: bridge